services:
    devpack_gedmo_tree_recalc.command:
        class: DevPack\Command\GedmoTreeRecalcCommand
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: 'console.command', command: 'devpack:gedmo:tree:recalc' }
